import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  input: {
    flexDirection: 'row',
    padding:15,
    alignItems:'center',
    borderRadius:7,
    borderWidth:1.5,
    alignSelf:'center',
    width:350,
    fontSize:15,
    position:'relative',
  },
  textforinput: {
    flexDirection: 'row',
    padding:10,
    fontWeight: 'bold',
    fontSize:20,
  },
  createAccounttextdesignfortop:{
    color: 'black',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 30,
    marginBottom: 20,
    paddingTop:50,
  },
  createAccountButton:{
    backgroundColor: '#6730c5',
    padding: 12, 
    borderRadius:10,
    marginTop: 10,
    width : 350,
    borderWidth:1,
    alignSelf :'center',
  },
  passwordContainer:{
    width: 350,
    alignSelf: 'center',
    position: 'relative',
    justifyContent: 'center',
  },
  visibility:{
    position: 'absolute',
    right: 15,
    height: '100%',
    justifyContent: 'center',
  },
loginlink: {
    color: '#7c3aed',
    fontWeight: '600',
  },
loginContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    width: '100%',
  },
Alreadysignedup: {
    fontSize: 15,
    color: 'black',
    textAlign: 'center',
  },
welcomebacktextdesignfortop:{
    color: 'black',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 40,
    paddingTop:50,
  },
  loginttextdesignfortop:{
    color: 'black',
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 20,
    marginBottom: 20,
  },
  forgotpasswordstyle:{
  color:'#7c3aed',
  textAlign:'right',
  paddingRight:20,
  paddingTop:10,
  },
  loginbutton:{
    backgroundColor: '#6730c5',
    padding: 10,
    borderRadius:10,
    marginTop: 10,
    width : 350,
    borderWidth:0.7,
    alignSelf :'center',
  },
  signup: {
    fontSize: 15,
    color: '#697079',
    textAlign: 'center',
  },
  continueButton:{
    backgroundColor: '#6730c5',
    padding: 15,
    borderRadius:10,
    marginTop: 50,
    width : 300,
    borderWidth:1,
    alignSelf :'center',
  },
  output: {
    borderWidth: 1,
    padding: 50,
    marginTop: 100,
    color: 'white',
    alignSelf: 'center',
  },
  criteria:{ 
    paddingHorizontal: 20,
    flexDirection: 'row', 
    alignItems: 'center'
  },
  textForCriterias:{
    fontSize: 15,
    paddingBottom: 10,
    paddingTop: 10,
  },
  imagebox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 10,
  },
  image:{
    width: 500,
    height: 200,
    alignSelf:'center',
    borderRadius: 10,
    flex: 1,
  },
  textforinputintripsdetails: {
    flexDirection: 'row',
    padding:10,
    paddingLeft:15,
    fontSize:15,
    paddingTop:25,
  },
    textforinputintrips: {
    flexDirection: 'row',
    padding:10,
    paddingLeft:15,
    fontSize:15,
    },
  NextButton:{
    backgroundColor: '#6730c5',
    padding: 12, 
    borderRadius:10,
    marginTop: 10,
    width : 350,
    alignSelf :'center',
  },
  ReasonForTripButton:{
    marginTop:20, 
    marginBottom:20,  
    borderColor:'#bd9cf6', 
    padding:10, 
    borderRadius:10,
    borderWidth:1,
    margin: 20,
    paddingHorizontal: 25,
  },
  ReasonForTripStayOnTheSameLine:{
    justifyContent: 'space-between',
    alignSelf:'center',
    flexDirection: 'row',
  },
  ReasonForTripIsPressed:{
    borderColor:'#a77bf3',
    backgroundColor:'#e9defc',
  },
  designforcreateanddetailsoftriptriptext:{
    fontSize:25,
    fontWeight:'500',
  },
  arrowforback:{
    height: 36,
    width: 36,
    justifyContent:'center',
    alignItems:'center',
    borderRadius: 18,
    backgroundColor: '#d9dbdd',
    marginRight: 5,
    marginLeft: 5,
  },
  arrowforbackandcreatenewtripcontainer:{
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 15,

  },
  orblockdesign: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
    paddingHorizontal: 20,
    marginTop:20,
  },
  orlines: {
    flex: 1,
    height: 1,
    backgroundColor: '#8f949b',
  },
  ortextdesigh:{
    color:'#8f949b',
    paddingLeft:10,
    paddingRight:10,
  },
  appleAndGoogleContainer:{
    alignSelf:'center',
    alignItems:'center',
    borderWidth:1,
    borderRadius:5,
    borderColor:'#8f949b',
    padding:10,
    margin:10,
    width:350,
    justifyContent:'center',
    flexDirection: 'row',
  },
  appleAndGoogleTextcontainer:{
    paddingLeft:10,
    fontSize:15,
    fontWeight:'500',
  }
});
