import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  input: {
    flexDirection: 'row',
    padding:15,
    alignItems:'center',
    borderRadius:7,
    borderWidth:1.5,
    alignSelf:'center',
    width:350,
    fontSize:15,
    position:'relative',
  },
  textforinput: {
    flexDirection: 'row',
    padding:10,
    fontWeight: 'bold',
    fontSize:20,
  },
  createAccounttextdesignfortop:{
    color: 'black',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 30,
    marginBottom: 20,
    paddingTop:50,
  },
  createAccountButton:{
    backgroundColor: '#6730c5',
    padding: 12, 
    borderRadius:10,
    marginTop: 10,
    width : 350,
    borderWidth:1,
    alignSelf :'center',
  },
  passwordContainer:{
    width: 350,
    alignSelf: 'center',
    position: 'relative',
    justifyContent: 'center',
  },
  visibility:{
    position: 'absolute',
    right: 15,
    height: '100%',
    justifyContent: 'center',
  },
  loginlink: {
    color: '#7c3aed',
    fontWeight: '600',
  },
  loginContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    width: '100%',
  },
  Alreadysignedup: {
    fontSize: 15,
    color: 'black',
    textAlign: 'center',
  },
  welcomebacktextdesignfortop:{
    color: 'black',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 40,
    paddingTop:50,
  },
  loginttextdesignfortop:{
    color: 'black',
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 20,
    marginBottom: 20,
  },
  forgotpasswordstyle:{
  color:'#7c3aed',
  textAlign:'right',
  paddingRight:20,
  paddingTop:10,
  },
  loginbutton:{
    backgroundColor: '#6730c5',
    padding: 10,
    borderRadius:10,
    marginTop: 10,
    width : 350,
    borderWidth:0.7,
    alignSelf :'center',
  },
  signup: {
    fontSize: 15,
    color: '#697079',
    textAlign: 'center',
  },
  continueButton:{
    backgroundColor: '#6730c5',
    padding: 15,
    borderRadius:10,
    marginTop: 50,
    width : 300,
    borderWidth:1,
    alignSelf :'center',
  },
  output: {
    borderWidth: 1,
    padding: 50,
    marginTop: 100,
    color: 'white',
    alignSelf: 'center',
  },
  criteria:{ 
    paddingHorizontal: 20,
    flexDirection: 'row', 
    alignItems: 'center'
  },
  textForCriterias:{
    fontSize: 15,
    paddingBottom: 10,
    paddingTop: 10,
  },
  imagebox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 10,
  },
  image:{
    width: 500,
    height: 200,
    alignSelf:'center',
    borderRadius: 10,
    flex: 1,
  },
  textforinputintripsdetails: {
    flexDirection: 'row',
    padding:10,
    paddingLeft:15,
    fontSize:15,
    paddingTop:25,
  },
    textforinputintrips: {
    flexDirection: 'row',
    padding:10,
    paddingLeft:15,
    fontSize:15,
    },
  NextButton:{
    backgroundColor: '#6730c5',
    padding: 12, 
    borderRadius:10,
    marginTop: 10,
    width : 350,
    alignSelf :'center',
  },
  ReasonForTripButton:{
    marginTop:20, 
    marginBottom:20,  
    borderColor:'#bd9cf6', 
    padding:10, 
    borderRadius:10,
    borderWidth:1,
    margin: 20,
    paddingHorizontal: 25,
  },
  ReasonForTripStayOnTheSameLine:{
    justifyContent: 'space-between',
    alignSelf:'center',
    flexDirection: 'row',
  },
  ReasonForTripIsPressed:{
    borderColor:'#a77bf3',
    backgroundColor:'#e9defc',
  },
  designforcreateanddetailsoftriptriptext:{
    fontSize:25,
    fontWeight:'500',
  },
  arrowforback:{
    height: 36,
    width: 36,
    justifyContent:'center',
    alignItems:'center',
    borderRadius: 18,
    backgroundColor: '#d9dbdd',
    marginRight: 5,
    marginLeft: 5,
  },
  arrowforbackandcreatenewtripcontainer:{
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 15,

  },
  orblockdesign: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
    paddingHorizontal: 20,
    marginTop:20,
  },
  orlines: {
    flex: 1,
    height: 1,
    backgroundColor: '#8f949b',
  },
  ortextdesigh:{
    color:'#8f949b',
    paddingLeft:10,
    paddingRight:10,
  },
  appleAndGoogleContainer:{
    alignSelf:'center',
    alignItems:'center',
    borderWidth:1,
    borderRadius:5,
    borderColor:'#8f949b',
    padding:10,
    margin:10,
    width:350,
    justifyContent:'center',
    flexDirection: 'row',
  },
  appleAndGoogleTextcontainer:{
    paddingLeft:10,
    fontSize:15,
    fontWeight:'500',
  },
  lagosSolotext:{
    textAlign: 'center',
    fontWeight: '100',
    fontSize: 20,
  },
  statustext:{
    textAlign: 'center',
    fontSize: 30,
    fontWeight:'400',
  },
  caremessagetext:{
    textAlign: 'center',
    fontSize: 13,
    marginBottom: 50,
    fontWeight:'400',
  },
  checkinAndViewButtonText:{
    color: 'white',
    textAlign: 'center',
    fontSize : 20,
    fontWeight:'500',
  },
  gracePeriodbox:{
    alignItems:'flex-start',
    borderWidth:1,
    borderColor:'#8f949b',
    padding:40, 
    borderRadius:20,
    margin: 20,
    paddingHorizontal: 20,
  },
  expectedAndEndSameLine:{
    justifyContent:'space-between',
    marginHorizontal:30,
    flexDirection: 'row',
    paddingBottom:10,
  },
  expectedAndEndSameLineInAlerts:{
    justifyContent:'space-evenly',
    alignContent:'space-between',
    flexDirection: 'row',
    textAlign:'center',
    alignItems:'center'
  },
  cauimage:{
    marginTop:30,
    width: 500,
    height: 175,
    alignSelf:'center',
    borderRadius: 10,
  },
  triggerButton:{
    borderWidth:1,
    borderColor:'#f97316',
    padding:10, 
    borderRadius:12,
    margin: 20,
    marginTop:10,
  },
  notififiedContactsText:{
    alignItems:'center',
    paddingTop:40,
    fontSize:20,
  },
  mapimage: {
    alignItems: 'center',
    margin: 10,
    width: 500,
    height: 375,
    alignSelf:'center',
    borderRadius: 10,
  },
  lastUpdateText:{
    textAlign: 'left',
    fontWeight: '100',
    marginBottom: 20,
    paddingLeft:20,
    fontSize:15,
  },
  alertTriggeredHeader: {
    color: '#ef4444',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 22,
    marginTop: 10,
  },
  notifiedGreenText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#10b981',
  },
  contactLeftSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contactAvatar: {
    width: 55,
    height: 55,
  },
  alertIconContainer: {
    backgroundColor: '#ef4444',
    width: 65,
    height: 65,
    borderRadius: 32.5,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
    marginBottom: 20,
    // Optional shadow effect
    shadowColor: '#ef4444',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  emergencyTitleText: {
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '700',
    color: '#000000',
    lineHeight: 30,
  },
  emergencySubtitleText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#1f2937',
    fontWeight: '500',
    marginTop: 15,
    marginHorizontal: 40,
    lineHeight: 22,
  },
  contactsListContainer: {
    marginTop: 30,
    paddingHorizontal: 25,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
  },
  contactNameText: {
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 15,
    color: '#000',
  },
  viewLiveLocationButton: {
    backgroundColor: '#6b21a8',
    paddingVertical: 16,
    borderRadius: 14,
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewLiveLocationButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
  },
}
);
